### ISSUE TITLE
Fails if a field is larger than bufio.MaxScanTokenSize 

### ISSUE THREAD

**Issue by jmunson** [yehezkel/gohl7#1]
If you're trying to parse a hl7 file that contains a really long field (for example, a base64 encoded pdf), gohl7 returns the error "bufio.Scanner: token too long".

**Comment by scottjbarr** [comment]
Apparently http://golang.org/pkg/bufio/#Reader.ReadLine is more suitable for arbitrary sized tokens.

**Comment by yehezkel** [comment]
Hello @jmunson thanks for reporting this i got away from this project and just recently i saw your bug filing, thanks again, i am  rewriting this. and this bug will no longer be relevant as i am not using bufio anymore
