### ISSUE TITLE
panic: bufio.Scan: 100 empty tokens without progressing

### ISSUE THREAD

**Issue by scottjbarr** [yehezkel/gohl7#4]
EOF is being missed in later versions of Go. I'm working with 1.6.3 and 1.7rc2.

Apparently there were changes to how scan functions dealt with EOF as of GO 1.4 (See comments in https://git.ustclug.org/zhsso/go/commit/590f5283762a6e80796c3ae2bde410319162cb45)

Running `go test` results in the panic below (truncated)

```
$ go test
--- FAIL: TestFirst (0.00s)
panic: bufio.Scan: 100 empty tokens without progressing [recovered]
    panic: bufio.Scan: 100 empty tokens without progressing
```

**Comment by yehezkel** [comment]
due to rewrite this is no longer relevant, thanks
